language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - source ./.travis.sh
  - psql -c 'create database testing_travis;' -U postgres

script: 
  - python -m pytest

after_success:
 - coveralls