"""empty message

Revision ID: 291d1d7dcd27
Revises: 6c044b78a198
Create Date: 2018-05-05 11:31:57.155783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291d1d7dcd27'
down_revision = '6c044b78a198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
