"""empty message

Revision ID: 5c444a6fb079
Revises: 
Create Date: 2018-05-03 15:10:31.763250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c444a6fb079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.String(length=50), nullable=True),
    sa.Column('meal_name', sa.String(length=50), nullable=True),
    sa.Column('meal_price', sa.Integer(), nullable=True),
    sa.Column('meal_category', sa.String(length=50), nullable=True),
    sa.Column('meal_day', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.String(length=50), nullable=True),
    sa.Column('menu_name', sa.String(length=50), nullable=True),
    sa.Column('menu_price', sa.Integer(), nullable=True),
    sa.Column('menu_category', sa.String(length=50), nullable=True),
    sa.Column('menu_day', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('order_name', sa.String(length=50), nullable=True),
    sa.Column('order_price', sa.Integer(), nullable=True),
    sa.Column('order_category', sa.String(length=50), nullable=True),
    sa.Column('order_day', sa.String(length=50), nullable=True),
    sa.Column('order_qty', sa.Integer(), nullable=True),
    sa.Column('order_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('menu')
    op.drop_table('meals')
    # ### end Alembic commands ###
