"""empty message

Revision ID: 6c044b78a198
Revises: bbbc59933d39
Create Date: 2018-05-05 10:59:56.757259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c044b78a198'
down_revision = 'bbbc59933d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_time_ordered_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_time_ordered_key', 'orders', ['time_ordered'])
    # ### end Alembic commands ###
