"""empty message

Revision ID: fca3dc7f41e1
Revises: 291d1d7dcd27
Create Date: 2018-05-05 13:38:32.062310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca3dc7f41e1'
down_revision = '291d1d7dcd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_by')
    # ### end Alembic commands ###
